skillMetadata:
  sections:
    - name: Options
      fields:
        - type: label
          label: You need a Google account and must create a <a href=https://console.developers.google.com/start/api?id=kgsearch.googleapis.com&credential=client_key>API key first</a>
        - name: api_key
          type: text
          label: Google API key
          value: ""
          placeholder:
